In [9]:
import numpy as np
import pandas as pd

Abbiamo una lista di **liste**: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]. Che tipo di struttura dati o matematica potrebbe rappresentare? Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?

In [36]:
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] # Dato di tipo tabellare, potenziale DataFrame
print(mat)
print(type(mat))

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
<class 'list'>


In [38]:
df = pd.DataFrame(mat, index=['A','B','C'], columns=[1, 2, 3, 4, 5])
df

1   2   3   4   5
A   0   1   2   3   4
B   5   6   7   8   9
C  10  11  12  13  14

In [40]:
df.shape

(3, 5)

In [46]:
mat_2 = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
mat_2

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [50]:
mat_2[1][0] # per accedere ad un singolo elemento

5

Importiamo il **modulo math** e proviamo a usare le funzioni **.sin()**, **.cos()**, **.factorial()** e la variabile **.pi.** La riconoscete?

In [53]:
import math as m

In [55]:
m.sin(30)

-0.9880316240928618

In [57]:
m.cos(30)

0.15425144988758405

In [67]:
m.factorial(3)

6

In [69]:
m.pi # pi greco

3.141592653589793

Proviamo a eseguire **math.degrees(math.pi)**. Qual è e cosa significa il risultato? Per saperne di più su questa funzione possiamo usare **help(math.degrees)**.

In [74]:
m.degrees(m.pi)

180.0

In [76]:
help(m.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



L'azienda **Object SpA** ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] trasformiamola in un **array NumPy** (casting): **lst = np.array(lst)** e rispondiamo alle domande del CEO della Object SpA: qual è stata la vendita massima mensile? E quella minima? Quali sono le vendite mensili maggiori di 5000 oggetti? E quante ne sono? E quali sono le vendite minori di 3000 oggetti? In media quanti oggetti sono stati venduti al mese?

In [81]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst = np.array(lst)

In [83]:
lst

array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100,
       5350])

In [108]:
np.max(lst)  # valore massimo dell'array

np.int64(8150)

In [110]:
np.min(lst)  # valore minimo dell'array

np.int64(1280)

In [152]:
vendite_mensili_maggiori = lst > 5000

In [166]:
check_vendite = lst[vendite_mensili_maggiori]  # creo una variabile che filtra solo le vendite maggiori di 5000

In [168]:
print(check_vendite)
print(check_vendite.size)

[5500 7200 6410 8150 7100 5350]
6


In [170]:
vendite_mensili_minori = lst < 3000  # creo una variabile che filtra solo le vendite minori di 3000

In [172]:
check_vendite_2 = lst[vendite_mensili_minori]

In [174]:
print(check_vendite_2)
print(check_vendite_2.size)

[2000 1280 1900 2500]
4


In [201]:
vendite_medie_annue = round(np.mean(lst), 2)    # vendite medie annue (arrotondate al secondo decimale)
print(f'Vendite_medie_annue: {vendite_medie_annue}')

Vendite_medie_annue: 4634.17


Consideriamo il seguente **dizionario**: fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}.
Consideriamo ora la seguente **Series**: fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005)).
Possiamo accedere alle stesse informazioni allo stesso modo : fatturati_dict[1997], fatturati_series[1997].
Dunque qual è la **differenza** tra i due tipi di dato?
Cosa potremmo fare con la **Series** che non possiamo fare con il **dizionario**?

In [179]:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

In [186]:
fatturati_dict

{1997: 12000,
 1998: 15000,
 1999: 20000,
 2000: 23000,
 2001: 25000,
 2002: 17000,
 2003: 14000,
 2004: 21000}

In [188]:
fatturati_series

1997    12000
1998    15000
1999    20000
2000    23000
2001    25000
2002    17000
2003    14000
2004    21000
dtype: int64

In [184]:
print(fatturati_dict[1997])
print(fatturati_series[1997])

12000
12000


In [235]:
print(pd.Series.mean(fatturati_series))  # Nelle Series possiamo fare operazioni su tutti gli elementi contemporaneamente (MASKING)
print(pd.Series.max(fatturati_series))
print(pd.Series.min(fatturati_series))
print(pd.Series.count(fatturati_series))

18375.0
25000
12000
8


In [237]:
print(fatturati_dict.items())  # Nel dizionario non possiamo fare operazioni, solo visualizzazione
print(fatturati_dict.keys())
print(fatturati_dict.values())

dict_items([(1997, 12000), (1998, 15000), (1999, 20000), (2000, 23000), (2001, 25000), (2002, 17000), (2003, 14000), (2004, 21000)])
dict_keys([1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004])
dict_values([12000, 15000, 20000, 23000, 25000, 17000, 14000, 21000])


L'azienda **Object SpA** ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un **ndarray** (import numpy as np): stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]). L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo con un **ciclo for** e con il **masking**.

In [239]:
stipendi = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])
stipendi

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [247]:
# METODO con ciclo for:
for stipendio in stipendi:
    stipendio_raddoppiato = stipendio * 2
    print(stipendio_raddoppiato, end= ' ')

200 400 600 800 1000 1200 1400 1600 1800 2000 

In [249]:
# METODO con masking:
stipendio_raddoppiato_2 = stipendi * 2
stipendio_raddoppiato_2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

Scrivere un programma che, data una lista di numeri, fornisca in output i **tre numeri più grandi**; gestire il caso in cui la lista sia più corta di tre, e quando uno o più dei numeri selezionati sono uguali.

In [257]:
lista_numeri = [0, 1, 1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8]
lista_numeri

[0, 1, 1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8]

In [273]:
lista_numeri = list(set(lista_numeri)) # Trasformo la lista in set, così da rimuovere i valori duplicati, e poi di nuovo in lista
if len(lista_numeri) > 3:
    print(lista_numeri[-3:])
else:
    print('Lista troppo corta')

[6, 7, 8]


Scrivere un programma che in **input** acquisisce una lista di numeri e un numero K, mentre in **output** dovrà restituire la media di tutti i numeri nella lista maggiori o uguali a K. Se non ce ne dovesse essere nessuno, dovrà stampare a schermo un messaggio adeguato.

In [338]:
import numpy as np
K = int(input('Numero inserito: '))  # inizializzazione
listozza_numeri = np.array([4, 13, 15, 65, 19, 20, 58, 7, 43, 2, 33])

numeri_maggiori_di_K = listozza_numeri > K
numeri_maggiori_di_K = listozza_numeri[numeri_maggiori_di_K]
if (numeri_maggiori_di_K > K).all():
    print(np.mean(numeri_maggiori_di_K))

Numero inserito:  60


65.0


In [340]:
numeri_maggiori_di_K # Lista che si aggiorna in base a K

array([65])

Scrivere un programma che, data una lista di numeri, come output stamperà lo stesso numero di **asterischi** su righe diverse, ottenendo una semplice visualizzazione grafica; ad esempio, supponendo di avere il seguente input: numeri = [5, 2, 3, 4], l'output sarà: ***** , ** , *** , 
 **** .

In [347]:
input_numeri = [5, 2, 3, 4]  # inizializzazione

for numero in input_numeri:
    print(('*')* numero)   # ripetizione di una stringa

*****
**
***
****


Abbiamo una lista di **codici fiscali**: lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]. Trovare i codici fiscali che contengono **"95"**, metterli in una lista, e alla fine stamparla; poi, per ognuno di essi, stampare a video i caratteri relativi al nome e quelli relativi al cognome.

In [350]:
lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]

In [362]:
lista_designata = []  # qui metteremo i CF che rispettano la condizione richiesta

for codice_fiscale in lista_cf:
    if '95' in codice_fiscale:  # gli dico di cercarmi la stringa 
        print('CF individuato =', codice_fiscale)
        lista_designata.append(codice_fiscale)
        print('lista designata =', lista_designata)

CF individuato = ABCDEF95G01A123B
lista designata = ['ABCDEF95G01A123B']
CF individuato = STUVWX95Z04A654E
lista designata = ['ABCDEF95G01A123B', 'STUVWX95Z04A654E']
CF individuato = DEFGHI95J06A987G
lista designata = ['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']


In [388]:
lista_nomi = []  # qui metteremo le stringhe relative al nome
lista_cognomi = []  # qui metteremo le stringhe relative al cognome

for codice_fiscale in lista_cf:
    print(codice_fiscale[:3],',', end =' ')
    lista_nomi.append(codice_fiscale[:3])

print('lista nomi =', lista_nomi)

ABC , GHI , MNO , STU , XYZ , DEF , lista nomi = ['ABC', 'GHI', 'MNO', 'STU', 'XYZ', 'DEF']


In [416]:
for codice_fiscale in lista_cf:
    print(codice_fiscale[3:6],',', end =' ')
    lista_cognomi.append(codice_fiscale[3:6])

print('lista cognomi =', lista_cognomi)
# lista_cognomi.clear()       svuota la lista 

DEF , JKL , PQR , VWX , ABC , GHI , lista cognomi = ['DEF', 'JKL', 'PQR', 'VWX', 'ABC', 'GHI']


In [414]:
lista_cognomi.clear()

Abbiamo tre **liste** della stessa lunghezza, dove ogni elemento nella medesima posizione si riferisce ai dati dello stesso studente: studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"]; corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"]; edizioni = [1, 2, 3, 2, 2, 1, 3, 3]. Stampare a video tutti e soli gli studenti che frequentano una **prima edizione**; non tutti i dati potrebbero essere necessari.

In [430]:
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"]
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"]
edizioni = [1, 2, 3, 2, 2, 1, 3, 3]
# Gli elementi di ciascuna lista sono posizionali e Python, con la funzione ZIP, li riconosce come tali

In [432]:
for studente, corso, edizione in zip(studenti, corsi, edizioni):  # iteriamo su più liste contemporaneamente
    if edizione == 1:
        print(f'{studente} ha partecipato al corso di {corso}, edizione {edizione}')

Alex ha partecipato al corso di Cybersecurity, edizione 1
Faith ha partecipato al corso di Backend, edizione 1


Abbiamo una **lista di stringhe** di prezzi in dollari, che erroneamente sono stati scritti con il simbolo dell'euro: prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"] cambiare il simbolo dell'euro (€) in quello del dollaro ($) per ogni stringa nella lista; il risultato sarà memorizzato in un'altra lista.

In [448]:
prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"]
prezzi_in_dollaro = []

for prezzo in prezzi:
    if '€' in prezzo:
        prezzo_no_euro = prezzo.replace('€','')  # devo prima togliere la valuta
        prezzi_in_dollaro.append(prezzo_no_euro + '$')  # nella lista vuota, faccio concatenzaione tra prezzo e $
print(f'Prezzi in dollaro = {prezzi_in_dollaro}')

# nuova_lista = [prezzo.replace('€','$') for prezzo in prezzi]    Comprehension

Prezzi in dollaro = ['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


Abbiamo una **lista di studenti**: studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"]. Vogliamo dividere gli studenti in due squadre per un campionato di Uno nel seguente modo: selezioneremo i nomi in posizione pari per un squadra, e i nomi in posizione dispari per l'altra. Creiamo due liste per ogni squadra e alla fine visualizziamole.

In [450]:
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"]
squadra_pari = []
squadra_dispari = []
indice = 0

while indice < len(studenti):
    if indice % 2 == 0:
        squadra_pari.append(studenti[indice])
    else:
        squadra_dispari.append(studenti[indice])
    indice +=1
print(f'Componenti Squadra Pari: {squadra_pari}')
print(f'Componenti Squadra Dispari: {squadra_dispari}')
        

Componenti Squadra Pari: ['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
Componenti Squadra Dispari: ['Bob', 'Dan', 'Faith', 'Henry', 'John']


Abbiamo una **lista** con i guadagni degli ultimi 12 mesi (supponiamo da Gennaio a Dicembre): guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50]. Dobbiamo confrontare, stampando tutto a video, il **guadagno di ogni mese** con la media dei guadagni precedenti e specificare nell'output se il guadagno attuale è maggiore o minore della media dei precedenti. Esempio di un possibile output: Mese 1: 100 €, Mese 2: 90 € (media prec. : 100 € - il guadagno attuale è minore), Mese 3: 70 € (media prec. : 95 € - il guadagno attuale è minore).

In [460]:
guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50]
mesi = ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre']
media = [100, 95, 80, 55, 45, 65, 85, 105, 100, 50, 35, 50]  # me le sono calcolate da solo perchè non sapevo come fare

In [466]:
for guadagno, mese, media_mensile in zip(guadagni, mesi, media):
    
    print(f'mese: {mese}, guadagno: {guadagno}, media precedente: {media_mensile}---> il guadagno è ')

mese: Gennaio, guadagno: 100, media precedente: 100---> il guadagno è 
mese: Febbraio, guadagno: 90, media precedente: 95---> il guadagno è 
mese: Marzo, guadagno: 70, media precedente: 80---> il guadagno è 
mese: Aprile, guadagno: 40, media precedente: 55---> il guadagno è 
mese: Maggio, guadagno: 50, media precedente: 45---> il guadagno è 
mese: Giugno, guadagno: 80, media precedente: 65---> il guadagno è 
mese: Luglio, guadagno: 90, media precedente: 85---> il guadagno è 
mese: Agosto, guadagno: 120, media precedente: 105---> il guadagno è 
mese: Settembre, guadagno: 80, media precedente: 100---> il guadagno è 
mese: Ottobre, guadagno: 20, media precedente: 50---> il guadagno è 
mese: Novembre, guadagno: 50, media precedente: 35---> il guadagno è 
mese: Dicembre, guadagno: 50, media precedente: 50---> il guadagno è 


In [470]:
for guadagno_mensile in range(len(guadagni)):  # usiamo la funzione range
    guadagno_attuale = guadagni[guadagno_mensile]
    mese = guadagno_mensile + 1

    if guadagno_mensile == 0:
        print(f"Mese {mese}: {guadagno_attuale} €") # se il guadagno mensile è pari a 0 stampami solo il mese
    else:                 # altrimenti fammi la differenza tra la somma dei guadagni (step by step) e un determinato guadagno mensile
        media_prec = sum(guadagni[:guadagno_mensile]) / guadagno_mensile  
        confronto = "maggiore" if guadagno_attuale > media_prec else "minore"
        print(f"Mese {mese}: {guadagno_attuale} € (media precedente: {media_prec:.2f} € ---> il guadagno attuale è {confronto})")

Mese 1: 100 €
Mese 2: 90 € (media precedente: 100.00 € ---> il guadagno attuale è minore)
Mese 3: 70 € (media precedente: 95.00 € ---> il guadagno attuale è minore)
Mese 4: 40 € (media precedente: 86.67 € ---> il guadagno attuale è minore)
Mese 5: 50 € (media precedente: 75.00 € ---> il guadagno attuale è minore)
Mese 6: 80 € (media precedente: 70.00 € ---> il guadagno attuale è maggiore)
Mese 7: 90 € (media precedente: 71.67 € ---> il guadagno attuale è maggiore)
Mese 8: 120 € (media precedente: 74.29 € ---> il guadagno attuale è maggiore)
Mese 9: 80 € (media precedente: 80.00 € ---> il guadagno attuale è minore)
Mese 10: 20 € (media precedente: 80.00 € ---> il guadagno attuale è minore)
Mese 11: 50 € (media precedente: 74.00 € ---> il guadagno attuale è minore)
Mese 12: 50 € (media precedente: 71.82 € ---> il guadagno attuale è minore)
